### ISSUE TITLE
Does srs-milter support multi-domain mail servers?

### ISSUE THREAD

**Issue by RandieM** [emsearcy/srs-milter#4]
This is more of a question rather than an issue. 
I am looking for a SRS solution for a multi-domain (shared mail hosting) server. If I understand well, this plug-in only supports single domain mail servers. Please correct me if I am wrong.

**Comment by emsearcy** [comment]
Depends how "white label" you want this to be. SRS only affects the envelope sender / return path, not the "From" header which is visible in email clients.  This milter only supports a single domain choice for the rewritten envelope sender (which is how bounces get back to your MTA), but this works fine with a mail server that accepts and forwards mail for multiple virtual_domains or relay_domains.

If you want the envelope sender for outgoing mail to be "white labeled" such that each customer's domain is used as the "hidden" envelope sender address for return bounces ... then no that isn't supported by srs-milter.

**Comment by RandieM** [comment]
@emsearcy, thanks a lot for your answer.

Unfortunately, using a global return path would not make much sense in a mail server with a few hundreds of customer domains.

May I ask why a "white-labelled" envelope sender is not possible? Is it because it is something complicated to program or is it technically impossible?

**Comment by vokac** [comment]
Support for single srs domain was a design choice because srs-milter was originally made to support one organization with only one domain + subdomains. I think that without further assumptions about your internal mail flow it is not generally possible to use different return domains for SRS (MAIL FROM envelope address for "forwarded" mail) - milter plugin basically gets original MAIL FROM header that can be arbitrary and RCPT TO that is also arbitrary for forwarded mail - as far as I know there is nothing that is related to the original recipient (see http://www.postfix.org/MILTER_README.html#macros).

On the other hand MAIL FROM address is basically hidden from end user and you could use just single srs.yourdomain.com to deal with all bounced mails - it'll be used only for mail delivery failures in case there are problems to delivery your forwarded SRS fixed email at the final destination - SRS recipient in these bounces must be reverted to the mail address of original sender and forwarded back there.

**Comment by RandieM** [comment]
@vokac, many thanks for your detailed explanation. I will give your suggestion a try, as soon as I find some time.
